### ISSUE TITLE
Dashboard doesn't detect Ledger with latest Polkadot app (v100.0.5)

### ISSUE THREAD

**Issue by Juanma0x** [polkadot-cloud/polkadot-staking-dashboard#2180] opened 2024-07-03 07:34 UTC
After connecting the Ledger to the PC and opening the latest Polkadot Ledger app (v100.0.5), the Staking Dashboard does not detect that the device is connected.

The same issue occurs when the user opens the "Migration app."

![image](https://github.com/polkadot-cloud/polkadot-staking-dashboard/assets/120041850/5c010e87-d679-4338-bd42-7fc3cd6d6ce6)

However, when using the "Legacy" Kusama Ledger app, the Staking Dashboard detects the device and imports the account successfully.

**Comment by An0b1s** [comment] 2024-07-03 08:11
i can confirm this issue. When i try to bond more DOTs, the Dashboard can't connect with the Ledger Wallet. When i click "confirm" -> nothing.

There's only the message: Open the Polkadot app on your Ledger device. -> The App is open on the Ledger..

<img width="599" alt="Bildschirmfoto 2024-07-03 um 10 08 19" src="https://github.com/polkadot-cloud/polkadot-staking-dashboard/assets/99994263/32818d1a-7e5b-4c78-8eea-5fe3d079dae9">

**Comment by Tanariel** [comment] 2024-07-03 11:18
Same problem here with the latest Polkadot Ledger app (v100.0.5), it constantly ask to open the polkadot app on the device even though it is open.

**Comment by rossbulat** [comment] 2024-07-03 18:33
Staking Dashboard had no pre release access to the new Ledger app so it is not currently supported. Please remain on previous Ledger app version to use with the Dashboard for now.

**Comment by Tanariel** [comment] 2024-07-04 04:35
The update was triggered because trying to stack more dot and sign it with the ledger gave a "wrong version" error. 

So not upgrading the ledger won't help either.

**Comment by rossbulat** [comment] 2024-07-04 05:55
> The update was triggered because trying to stack more dot and sign it with the ledger gave a "wrong version" error. 
> 
> So not upgrading the ledger won't help either. 

Thank you for clarifying this, I am currently recovering from an illness but will attempt to treat this issue as a priority. 

I think a public beta of the new Ledger app and/or migration documentation prepared for JS/TS applications would have been very useful to have prior to release. Unfortunately, despite the best efforts of some people, the clarifications of what exactly needs to be done for the new version have just not been there for Dapps, and this has prolonged this issue not just for the dashboard but other Dapps too.

**Comment by Juanma0x** [comment] 2024-07-04 07:13
> Please remain on previous Ledger app version to use with the Dashboard for now.

I'm afraid that won't allow users to issue any extrinsic since the old Polkadot Ledger app is not compatible with the current runtime upgrade.

> the clarifications of what exactly needs to be done for the new version have just not been there for Dapps

Bad news indeed.

> I am currently recovering from an illness

Get well soon, Ross.

**Comment by rossbulat** [comment] 2024-07-06 06:53
This should have been resolved in https://github.com/polkadot-cloud/polkadot-staking-dashboard/pull/2181. Will leave this issue open a while longer in case other issues arise.

**Comment by An0b1s** [comment] 2024-07-06 07:04
Hello @rossbulat 
Perfect. Now it works. Have a nice weekend

**Closed** 2024-07-06 09:37 UTC

**Comment by Tanariel** [comment] 2024-07-06 13:16
Working perfectly, thanks a lot !
